main:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Our team"
    url: "/team/"
    weight: 3

buttons:
  - name: "Book a call"
    url: "/contact"
    weight: 5

footer:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Our team"
    url: "/#"
    weight: 3
