title: "Advitspace"
description: "Advitspace is a consultancy built to help organisations understand, manage and improve their cyber risk."
images: 
  - "images/logo.png"

logo: "images/logo.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"


location:
  - "167-169 Great Portland Street, 5th Floor, London, United Kingdom, W1W 5PF"

contact:
  - "remus.sferle@advitspace.com"
  - "07398 791 377"

copyright: "© 2026 Advitspace All Rights Reserved"

