title: "Advitspace"
description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
images: 
  - "images/hero-image.png"

logo: "arrow-up.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  facebook: "#"
  linkedin: "#"

location:
  - "3891 Ranchview Dr. Richardson, California 62639"

contact:
  - "remus.sferle@advitspace.com"
  - "07398 791 377"

copyright: "© 2026 Advitspace All Rights Reserved"

